Add support dual insights method, that endpoints of ig_media_id and ig_user_id.
rakeshpatra/instagram_graph_api pull request #10
Opened 2020-10-22 02:54 UTC by himrock922

https://developers.facebook.com/docs/instagram-api/guides/insights

Also, 

```
Endpoints
The API consists of the following endpoints:

GET /{ig-media-id}/insights — gets metrics on a media object
GET /{ig-user-id}/insights — gets metrics on an Instagram Business Account or Instagram Creator account.
Refer to each endpoint's reference documentation for available metrics, parameters, and permission requirements.
```

This commit supported both endpoints.

Please review.

Regards.

2020-10-22 05:21 UTC, rakeshpatra requested changes
Thanks for the PR, would you mind making the suggested changes?

2020-10-22 05:21 UTC, rakeshpatra commented on lib/instagram_graph_api/client/insights.rb
> +      def insights(object_id, metrics: nil)
@himrock922 We will have to use type for `media` context which is not available here, also we will need the `METRIC_HASH` here.

2020-10-22 06:53 UTC, himrock922 commented
@rakeshpatra 
Hi, Thanks for the response.

My context wants use  `GET /{ig-user-id}/insights` and `GET /{ig-media-id}/insights` via instagram_graph_api.

https://developers.facebook.com/docs/instagram-api/reference/user/insights
https://developers.facebook.com/docs/instagram-api/reference/media/insights

if user-insights, I want use reqeust `audience_city` and `audience_country`
Also, media-insights, I want use reqeust `impressions` and `reach`.

First, I did try add insights method into user.rb.
But, This solution has connfflict problem for same name method.

Therefore, `insights` method wants partial.

2020-11-09 07:32 UTC, himrock922 commented
## Response

Test Code
```
    client = InstagramGraphApi.client(@facebook_auth.access_token)
    ig_accounts = client.connected_ig_accounts('biography,id,name,ig_id,follows_count,followers_count,media_count,profile_picture_url,username')
    instagram_users = ig_accounts.map.with_index(1) do |user, index|
      instagram_user = @facebook_auth.instagram_user_via_facebooks.build(uid: user["id"], ig_id: user["ig_id"], name: user["name"],
                                                                         username: user["username"], follows_count: user["follows_count"],
                                                                         followers_count: user["followers_count"], media_count: user["media_count"],
                                                                         profile_picture_url: user["profile_picture_url"], biography: user["biography"])
      instagram_user
    end
    # TODO: Instagramの投稿データを各IGユーザ全てを対象に取得する
    total_instagram_posts = instagram_users.map.with_index(1) do |user, index|
      user_instagram_posts = client.get_user_recent_media(user.uid, fields = "caption, children, comments_count, id, ig_id, is_comment_enabled, like_count,
                                                                         media_type, media_url, permalink, shortcode, timestamp")
      instagram_posts = user_instagram_posts.map.with_index(1) do |post, index|
        is_children_enabled = post["comments"].nil? ? false : true
        instagram_post = user.instagram_post_via_facebooks.build(post_id: post["id"], ig_id: post["ig_id"], caption: post["caption"], comments_count: post["comments_count"],
                                                                 like_count: post["like_count"], media_type: InstagramPostViaFacebook.media_types[post["media_type"].downcase],
                                                                 media_url: post["media_url"], permalink: post["permalink"], shortcode: post["shortcode"], thumbnail_url: post["thumbnail_url"],
                                                                 is_children_enabled: is_children_enabled, is_comment_enabled: post["is_comment_enabled"], timestamp: DateTime.parse(post["timestamp"]))
      end
      instagram_posts
    end
```

Instagram Graph API Object
```
[13] pry(#<Users::OmniauthCallbacksController>)> client
=> #<InstagramGraphApi::Client:0x00007f1798a717a8
 @access_token=
  "*****",
 @app_secret=nil,
 @raw_insights=
  [{"name"=>"impressions",
    "period"=>"lifetime",
    "values"=>[{"value"=>0}],
    "title"=>"インプレッション",
...etc
```

## media insights request and response

```
 client.insights(total_instagram_posts.flatten.first.post_id)
=> {"impressions"=>0, "reach"=>0}
```

## user insights request and response

```
client.insights(instagram_users.first.uid, metrics: "audience_city,audience_country&period=lifetime&since= 1604761200&until=1604847599")
=> {}
```

I'm sorry, my system had use test account, it wasn't happening from yesterday 00:00:00 to yesterday 23:59:59 anywhere.
Therefore user insights was response empty.

2020-11-09 09:05 UTC, rakeshpatra approved these changes

2020-11-09 09:06 UTC, merged